# Generated by Django 4.2.4 on 2024-09-24 05:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('article_name', models.CharField(max_length=100, unique=True)),
                ('slug', models.SlugField(max_length=200, unique=True)),
                ('description', models.TextField()),
                ('article_video_thumbnail', models.ImageField(blank=True, null=True, upload_to='thumbnails/')),
                ('article_video_url', models.URLField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Content',
            fields=[
                ('content_id', models.AutoField(primary_key=True, serialize=False)),
                ('content_name', models.CharField(max_length=255, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Course',
            fields=[
                ('course_id', models.AutoField(primary_key=True, serialize=False)),
                ('course_name', models.CharField(max_length=100, unique=True)),
                ('slug', models.SlugField(max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='VideoPlayer',
            fields=[
                ('video_played_id', models.AutoField(primary_key=True, serialize=False)),
                ('video_title', models.CharField(max_length=255)),
                ('video_description', models.TextField()),
                ('channel_name', models.CharField(max_length=100)),
                ('article_video_thumbnail', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='thumbnails', to='directory.article')),
                ('article_video_url', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='videos', to='directory.article')),
            ],
        ),
        migrations.CreateModel(
            name='UserPerformance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('watched_videos', models.ManyToManyField(to='directory.videoplayer')),
            ],
        ),
        migrations.CreateModel(
            name='Quiz',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.TextField()),
                ('options', models.TextField(help_text='Separate each option with a comma')),
                ('opt_values', models.TextField(help_text='Enter the option values corresponding to each option, separated by commas')),
                ('correct_options', models.TextField(help_text='Enter the correct options separated by commas')),
                ('article_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quizzes', to='directory.article')),
            ],
        ),
        migrations.AddField(
            model_name='article',
            name='course_name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='directory.course'),
        ),
    ]
