# Generated by Django 4.2.4 on 2024-09-24 08:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('directory', '0002_hyperlink_article_hyperlinks'),
    ]

    operations = [
        migrations.AddField(
            model_name='hyperlink',
            name='article_name',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='hyperlinks_set', to='directory.article'),
        ),
        migrations.AlterField(
            model_name='article',
            name='hyperlinks',
            field=models.ManyToManyField(blank=True, related_name='articles', to='directory.hyperlink'),
        ),
    ]
