# Generated by Django 4.2.4 on 2024-09-24 15:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('directory', '0005_rename_article_name_quiz_article_article_quiz_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='contents',
            field=models.ManyToManyField(blank=True, related_name='articles', to='directory.content'),
        ),
        migrations.AlterField(
            model_name='content',
            name='article',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='articles', to='directory.article'),
        ),
    ]
