# Generated by Django 4.2.4 on 2024-09-25 05:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('directory', '0006_alter_article_contents_alter_content_article'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='total_videos',
            field=models.PositiveIntegerField(null=True),
        ),
        migrations.AddField(
            model_name='userperformance',
            name='course',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='course', to='directory.course'),
        ),
        migrations.AlterField(
            model_name='content',
            name='article',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='content', to='directory.article'),
        ),
    ]
