# Generated by Django 4.2.4 on 2024-09-25 06:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('directory', '0007_course_total_videos_userperformance_course_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='videoplayer',
            old_name='article_video_url',
            new_name='article',
        ),
        migrations.RemoveField(
            model_name='videoplayer',
            name='article_video_thumbnail',
        ),
    ]
