# Generated by Django 4.2.4 on 2024-09-27 05:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('directory', '0008_rename_article_video_url_videoplayer_article_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='hyperlink',
            old_name='article_name',
            new_name='article',
        ),
    ]
