# Generated by Django 4.2.4 on 2024-10-14 08:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('directory', '0009_rename_article_name_hyperlink_article'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hyperlink',
            name='article',
        ),
        migrations.AddField(
            model_name='article',
            name='transcript',
            field=models.TextField(blank=True, null=True),
        ),
    ]
