# Generated by Django 4.2.4 on 2024-10-14 08:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('directory', '0010_remove_hyperlink_article_article_transcript'),
    ]

    operations = [
        migrations.AddField(
            model_name='hyperlink',
            name='article',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='hyperlinks_set', to='directory.article'),
        ),
    ]
